Feature/a 2
Stiehl-seine-Perlen/MemberManagement pull request #38
Opened 2023-06-23 20:03 UTC by chh3020

Finalize main

2023-06-23 20:20 UTC, philobmr commented on pom.xml
> +            <version>1.7.6-SNAPSHOT</version>
1.7.7 Snapshot

2023-06-23 20:20 UTC, philobmr requested changes

2023-06-23 20:20 UTC, philobmr commented on pom.xml
> +            <version>1.7.6-SNAPSHOT</version>
1.7.7

2023-06-23 20:23 UTC, philobmr approved these changes

2023-06-23 20:24 UTC, closed without merging

2023-06-24 09:04 UTC, Ainges reviewed
<del>this deleted features</del> was never merged...